import { DataStore } from './types';

export const defaultData: DataStore = {
  shareLinks: [
    {
      id: 'sl-1',
      name: 'James Adams — Full view',
      slug: 'james-adams',
      password: 'Avis-ML-2026',
      sections: { overview: true, findings: true, experiments: true, timeline: true },
      createdDate: 'Jun 20, 2026',
      lastAccessed: 'Today, 9:02 am',
    },
    {
      id: 'sl-2',
      name: 'Neil Morgan — Experiments + Metrics',
      slug: 'neil-morgan',
      password: 'Avis-ML-2024',
      sections: { overview: true, findings: false, experiments: true, timeline: false },
      createdDate: 'Jun 20, 2026',
      lastAccessed: 'Today, 9:02 am',
    },
  ],
  seenFindings: {},
  findings: [
    {
      id: 'f-1',
      title: 'Redirect loop on /checkout after promo code entry',
      description:
        'Users on mobile Safari (iOS 17+) are entering valid promo codes at checkout and being redirected back to the cart page instead of proceeding to payment. The loop repeats indefinitely — there is no error message shown to the user. The issue does not reproduce on Android or desktop browsers. Estimated impact: ~8% of mobile checkout sessions during peak promotional periods.',
      site: 'avis.com',
      severity: 'High',
      status: 'Reported',
      category: 'Checkout - UX bug',
      addedBy: 'Joey Unnold',
      dateAdded: 'Jun 30, 2026',
      lastUpdated: 'Today, 8:14am',
      images: [],
      isPinned: true,
      relatedFindingIds: ['f-2'],
      resolutionSteps: [
        {
          id: 'rs-1-1',
          stepNumber: 1,
          title: 'Finding reported to ABG engineering lead',
          description: 'Issue documented and shared with James Adams and the checkout team lead.',
          status: 'completed',
          completedDate: 'Jun 30, 2026',
        },
        {
          id: 'rs-1-2',
          stepNumber: 2,
          title: 'Root cause investigation underway',
          description: 'ABG engineering reviewing promo validation handler and redirect logic in checkout service.',
          status: 'in_progress',
        },
        {
          id: 'rs-1-3',
          stepNumber: 3,
          title: 'Fix deployed to staging',
          description: 'Awaiting engineering confirmation.',
          status: 'pending',
        },
        {
          id: 'rs-1-4',
          stepNumber: 4,
          title: 'Verified resolved in production',
          description: 'ML team to confirm fix and mark finding resolved.',
          status: 'pending',
        },
      ],
    },
    {
      id: 'f-2',
      title: 'ML model underpredicting demand on holiday weekends',
      description:
        'Fleet allocation model shows 12% gap vs actuals on Memorial Day weekend data. Retraining experiment initiated.',
      site: 'avis.com',
      severity: 'High',
      status: 'Fix in progress',
      category: 'Demand model',
      addedBy: 'Joey Unnold',
      dateAdded: 'Jun 29, 2026',
      lastUpdated: 'Today, 8:14am',
      images: [],
      isPinned: true,
      relatedFindingIds: ['f-1'],
      resolutionSteps: [
        {
          id: 'rs-2-1',
          stepNumber: 1,
          title: 'Anomaly detected in model output',
          description: 'Gap between predicted and actual demand flagged during Memorial Day review.',
          status: 'completed',
          completedDate: 'Jun 29, 2026',
        },
        {
          id: 'rs-2-2',
          stepNumber: 2,
          title: 'Retrain experiment initiated',
          description: 'Demand forecast v2 experiment started with extended holiday dataset.',
          status: 'in_progress',
        },
        {
          id: 'rs-2-3',
          stepNumber: 3,
          title: 'Model deployed to production',
          description: 'Pending experiment completion.',
          status: 'pending',
        },
      ],
    },
    {
      id: 'f-3',
      title: 'Session drop-off spike on Budget.com car class page',
      description:
        '23% increase in exits at the car class selection step. Correlated with recent UI change. Session replay analysis running.',
      site: 'budget.com',
      severity: 'Medium',
      status: 'Fix in progress',
      category: 'UX - Conversion',
      addedBy: 'Joey Unnold',
      dateAdded: 'Jun 28, 2026',
      lastUpdated: 'Jun 28, 2026',
      images: [],
      isPinned: true,
      relatedFindingIds: [],
      resolutionSteps: [
        {
          id: 'rs-3-1',
          stepNumber: 1,
          title: 'Drop-off spike identified',
          description: 'Anomaly flagged in session analytics dashboard.',
          status: 'completed',
          completedDate: 'Jun 28, 2026',
        },
        {
          id: 'rs-3-2',
          stepNumber: 2,
          title: 'Session replay analysis running',
          description: 'Reviewing recordings to identify friction points in car class selection.',
          status: 'in_progress',
        },
        {
          id: 'rs-3-3',
          stepNumber: 3,
          title: 'UI fix and A/B test',
          description: 'Pending replay findings.',
          status: 'pending',
        },
      ],
    },
    {
      id: 'f-4',
      title: 'Anomaly spike in rental return confirmations — EWR',
      description:
        'Confirmation emails delayed up to 40 min for EWR returns between Jun 10–15. Root cause identified as queue backlog.',
      site: 'avis.com',
      severity: 'Medium',
      status: 'Acknowledged',
      category: 'Email - Operations',
      addedBy: 'Janelle Kim',
      dateAdded: 'Jun 27, 2026',
      lastUpdated: 'Jun 27, 2026',
      images: [],
      isPinned: false,
      relatedFindingIds: [],
      resolutionSteps: [
        {
          id: 'rs-4-1',
          stepNumber: 1,
          title: 'Issue acknowledged',
          description: 'Queue backlog root cause confirmed by infrastructure team.',
          status: 'completed',
          completedDate: 'Jun 27, 2026',
        },
        {
          id: 'rs-4-2',
          stepNumber: 2,
          title: 'Queue capacity increase',
          description: 'Pending infrastructure team scheduling.',
          status: 'pending',
        },
      ],
    },
    {
      id: 'f-5',
      title: 'Loyalty point calculation error on multi-vehicle bookings',
      description:
        'Points were being applied per leg rather than per booking total. Fix deployed Jun 20, confirmed correct in production.',
      site: 'avis.com',
      severity: 'Low',
      status: 'Resolved',
      category: 'Loyalty - Backend',
      addedBy: 'Todd Barker',
      dateAdded: 'Jun 20, 2026',
      lastUpdated: 'Jun 20, 2026',
      images: [],
      isPinned: false,
      relatedFindingIds: [],
      resolutionSteps: [
        {
          id: 'rs-5-1',
          stepNumber: 1,
          title: 'Bug reported',
          description: 'Double-counting issue identified in loyalty engine.',
          status: 'completed',
          completedDate: 'Jun 18, 2026',
        },
        {
          id: 'rs-5-2',
          stepNumber: 2,
          title: 'Fix deployed to production',
          description: 'Calculation logic updated to apply points per booking total.',
          status: 'completed',
          completedDate: 'Jun 20, 2026',
        },
      ],
    },
  ],
  experiments: [
    {
      id: 'e-1',
      title: 'Demand forecast v2 — holiday model retrain',
      status: 'Running',
      owner: 'Joey',
      lastUpdated: 'Today, 7:50 am',
      startDate: 'Jun 29, 2026',
      site: 'avis.com',
      category: 'Demand model',
      severity: 'High',
      addedBy: 'Joey Unnold',
      hypothesis:
        'Retraining the fleet allocation model on an extended holiday dataset — including Memorial Day, July 4th, and Labor Day actuals — will reduce the gap between predicted and actual demand from 12% to under 4%.',
      approach:
        'The existing model was trained on 18 months of rental data excluding federal holiday windows. We are augmenting the training set with 3 years of holiday-period actuals (Memorial Day, July 4th, Labor Day, Thanksgiving) and retraining using the same XGBoost architecture. Validation is against a held-out Q2 2025 holiday set. A/B comparison will run in shadow mode — predictions are generated but not yet served to the fleet allocation system.',
      metrics: [
        { label: 'Forecast gap (actuals vs predicted)', value: '8.1%', subtext: '↓ 3.9pp improvement' },
        { label: 'Validation RMSE', value: '214', subtext: '↓ 28.9% reduction' },
        { label: 'Target gap (<4%)', value: '—', subtext: 'In progress — Full retrain pending', inProgress: true },
      ],
      outcome: 'Experiment still running. Partial results show improvement trend. Final outcome will be updated when full retrain completes.',
      outcomeStatus: 'Pending',
      relatedFindingIds: ['f-2'],
    },
    {
      id: 'e-2',
      title: 'Checkout funnel A/B — promo field placement',
      status: 'Reported',
      owner: 'Todd',
      lastUpdated: 'Jun 28, 2026',
      startDate: 'Jun 28, 2026',
      site: 'avis.com',
      category: 'Checkout - UX',
      severity: 'High',
      addedBy: 'Todd Barker',
      hypothesis: 'Moving the promo code field above the vehicle summary will reduce the redirect loop rate and increase promo code conversion by at least 15%.',
      approach: 'A/B test with 50/50 traffic split on mobile Safari. Control: existing promo field placement. Variant: promo field relocated above order summary. Measuring conversion rate, promo application success rate, and session drop-off.',
      metrics: [
        { label: 'Promo conversion rate', value: '—', subtext: 'Experiment not yet started', inProgress: true },
        { label: 'Session drop-off', value: '—', subtext: 'Experiment not yet started', inProgress: true },
      ],
      outcome: 'Experiment pending start. Awaiting fix for redirect loop (f-1) before launching.',
      outcomeStatus: 'Pending',
      relatedFindingIds: ['f-1'],
    },
    {
      id: 'e-3',
      title: 'Session replay analysis — Budget car class',
      status: 'Running',
      owner: 'Joey',
      lastUpdated: 'Today, 6:30 am',
      startDate: 'Jun 28, 2026',
      site: 'budget.com',
      category: 'UX - Conversion',
      severity: 'Medium',
      addedBy: 'Joey Unnold',
      hypothesis: 'Session replay analysis will identify the specific UI element(s) responsible for the 23% exit spike on the car class selection page.',
      approach: 'Reviewing 500 session recordings from Jun 18–28 using FullStory. Segmenting by device type, entry point, and rental duration. Heatmap analysis on the car class grid component.',
      metrics: [
        { label: 'Sessions reviewed', value: '312', subtext: 'of 500 target' },
        { label: 'Drop-off rate (control)', value: '18.4%', subtext: 'Baseline Jun 1–17' },
        { label: 'Drop-off rate (post-change)', value: '22.7%', subtext: '↑ 4.3pp increase' },
      ],
      outcome: 'Analysis in progress. Early results suggest the new image carousel is causing confusion on smaller mobile screens.',
      outcomeStatus: 'Pending',
      relatedFindingIds: ['f-3'],
    },
    {
      id: 'e-4',
      title: 'Anomaly threshold calibration — v3',
      status: 'Running',
      owner: 'Janelle',
      lastUpdated: 'Jun 25, 2026',
      startDate: 'Jun 21, 2026',
      site: 'avis.com',
      category: 'Anomaly detection',
      severity: 'Medium',
      addedBy: 'Janelle Kim',
      hypothesis: 'Recalibrating anomaly detection thresholds using a rolling 90-day baseline will reduce false positive alert rate by 30% while maintaining true positive detection.',
      approach: 'Comparing v2 fixed thresholds against v3 rolling percentile approach on historical anomaly data. Validation on Q1 2026 dataset with known anomalies labeled.',
      metrics: [
        { label: 'False positive rate', value: '12.3%', subtext: '↓ from 18.1% (v2)' },
        { label: 'True positive rate', value: '94.2%', subtext: '↑ from 91.7% (v2)' },
        { label: 'Alert volume reduction', value: '31.8%', subtext: 'vs v2 baseline' },
      ],
      outcome: 'Results show v3 meets both target criteria. Recommendation to promote to production in next deployment window.',
      outcomeStatus: 'Confirmed',
      relatedFindingIds: ['f-4'],
    },
  ],
  timelinePhases: [
    { id: 'tp-1', name: 'Discovery', startDate: 'May 18', endDate: 'May 31', color: '#234474', status: 'completed' },
    { id: 'tp-2', name: 'Analysis', startDate: 'Jun 1', endDate: 'Jun 20', color: '#7C3AED', status: 'completed' },
    { id: 'tp-3', name: 'Experimentation', startDate: 'Jun 21', endDate: 'Aug 1', color: '#059669', status: 'in_progress' },
    { id: 'tp-4', name: 'Synthesis', startDate: 'Aug 2', endDate: 'Aug 22', color: '#EA580C', status: 'upcoming' },
    { id: 'tp-5', name: 'Delivery', startDate: 'Aug 23', endDate: 'Sep 7', color: '#0891B2', status: 'upcoming' },
  ],
  milestones: [
    {
      id: 'm-1',
      title: 'Discovery complete — findings baseline established',
      date: 'May 31, 2026',
      status: 'Complete',
      description: '14 initial findings catalogued across avis.com, budget.com, and the fleet allocation model.',
      isHighlighted: false,
    },
    {
      id: 'm-2',
      title: 'Analysis phase complete — experiment backlog prioritised',
      date: 'Jun 20, 2026',
      status: 'Complete',
      description: '18 experiments scoped and prioritised. Anomaly threshold calibration v3 delivered as first result.',
      isHighlighted: false,
    },
    {
      id: 'm-3',
      title: 'Mid-engagement review with ABG leadership',
      date: 'Jul 10, 2026',
      status: 'Upcoming',
      description: 'Progress review, results to date, and experiment pipeline walkthrough with James Adams and Neil Morgan.',
      isHighlighted: true,
    },
    {
      id: 'm-4',
      title: 'Experimentation complete — all experiments resolved',
      date: 'Aug 1, 2026',
      status: 'Upcoming',
      description: 'All running experiments concluded. Results compiled for synthesis phase.',
      isHighlighted: false,
    },
    {
      id: 'm-5',
      title: 'Final report and recommendations delivered',
      date: 'Sep 7, 2026',
      status: 'Upcoming',
      description: 'Full engagement findings, experiment outcomes, and prioritised recommendations delivered to ABG.',
      isHighlighted: false,
    },
    {
      id: 'm-6',
      title: 'Engagement close — handoff to ABG team',
      date: 'Sep 7, 2026',
      status: 'Upcoming',
      description: 'Model documentation, dashboard handoff, and implementation roadmap delivered.',
      isHighlighted: false,
    },
  ],
};
